<a href="https://colab.research.google.com/github/Sara-Esm/PyTorch/blob/main/PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import torch

In [11]:
#create some tensores
t0 = torch.tensor(1000)
t1 = torch.tensor([9,8,7,6])
t3 = torch.tensor([[3,4,5], [5,6,7]])

print(t0)
print(t1)
print(t3)

tensor(1000)
tensor([9, 8, 7, 6])
tensor([[3, 4, 5],
        [5, 6, 7]])


In [14]:
#set datatype for the tensor
a = torch.ones((4,3), dtype=torch.int16)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [15]:
# get the tensor size
print(a.size())
print(a.shape)

torch.Size([4, 3])
torch.Size([4, 3])


In [16]:
# get the tensor dimension
print(a.ndimension())
print(a.ndim)

2
2
