<a href="https://colab.research.google.com/github/Sara-Esm/PyTorch/blob/main/PyTorch_Numpy_Bridge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
u = torch.tensor([2, 4])
v = torch.tensor([1, 4])
w = u * v
print(w)
print(w.shape)
print(w.ndim)

tensor([ 2, 16])
torch.Size([2])
1


In [13]:
a = torch.ones(4, 3, 2)
b = a * torch.rand(   3, 2)
print(b)

tensor([[[0.6878, 0.1851],
         [0.4956, 0.5465],
         [0.7733, 0.1759]],

        [[0.6878, 0.1851],
         [0.4956, 0.5465],
         [0.7733, 0.1759]],

        [[0.6878, 0.1851],
         [0.4956, 0.5465],
         [0.7733, 0.1759]],

        [[0.6878, 0.1851],
         [0.4956, 0.5465],
         [0.7733, 0.1759]]])


In [14]:
c = a * torch.rand(   3, 1)
print(c)

tensor([[[0.9548, 0.9548],
         [0.6753, 0.6753],
         [0.0133, 0.0133]],

        [[0.9548, 0.9548],
         [0.6753, 0.6753],
         [0.0133, 0.0133]],

        [[0.9548, 0.9548],
         [0.6753, 0.6753],
         [0.0133, 0.0133]],

        [[0.9548, 0.9548],
         [0.6753, 0.6753],
         [0.0133, 0.0133]]])


In [15]:
d = a * torch.rand(   1, 2)
print(d)

tensor([[[0.3837, 0.0308],
         [0.3837, 0.0308],
         [0.3837, 0.0308]],

        [[0.3837, 0.0308],
         [0.3837, 0.0308],
         [0.3837, 0.0308]],

        [[0.3837, 0.0308],
         [0.3837, 0.0308],
         [0.3837, 0.0308]],

        [[0.3837, 0.0308],
         [0.3837, 0.0308],
         [0.3837, 0.0308]]])


In [16]:
# switch between ndarrays and PyTorch tensors
import numpy as np
numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [17]:
# reverse example of converting from PyTorch tensor into ndarray
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.5893, 0.0878, 0.8047],
        [0.5866, 0.5164, 0.2494]])
[[0.5892752  0.08778143 0.80471236]
 [0.58655655 0.51638037 0.24939322]]


In [18]:
# using the same underlying memory
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.5892752   0.08778143  0.80471236]
 [ 0.58655655 17.          0.24939322]]
