<a href="https://colab.research.google.com/github/Sara-Esm/PyTorch/blob/main/PyTorch_Basic_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [5]:
# create 2 tensors
a = torch.tensor ([1 , 2])
b = torch.tensor ([3 , 4])
print(a)
print(b)

tensor([1, 2])
tensor([3, 4])


In [6]:
print (a + b)
print (a - b)

tensor([4, 6])
tensor([-2, -2])


In [7]:
c = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(c))
print(torch.ceil(c))
print(torch.floor(c))
print(torch.clamp(c, -0.5, 0.5))

Common functions:
tensor([[0.8227, 0.3225, 0.2384, 0.6512],
        [0.7278, 0.4712, 0.6949, 0.7096]])
tensor([[1., -0., 1., -0.],
        [-0., -0., -0., -0.]])
tensor([[ 0., -1.,  0., -1.],
        [-1., -1., -1., -1.]])
tensor([[ 0.5000, -0.3225,  0.2384, -0.5000],
        [-0.5000, -0.4712, -0.5000, -0.5000]])


In [8]:
x = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
print(x)
print(x.mean())

tensor([1., 2., 3., 4., 5.])
tensor(3.)


In [9]:
print(x.max())
print(x.min())

tensor(5.)
tensor(1.)


In [10]:
import numpy as np
x = torch.tensor([0, np.pi / 2, np.pi])
print(x)
print(torch.sin(x))
print(torch.cos(x))

tensor([0.0000, 1.5708, 3.1416])
tensor([ 0.0000e+00,  1.0000e+00, -8.7423e-08])
tensor([ 1.0000e+00, -4.3711e-08, -1.0000e+00])
